#!/usr/bin/env python3
"""生成 `src/alofa/tokenizer/unicode_data.mojo`。

预分词器要按 Qwen2 的规则切词，那条规则里有 `p{L}`、`p{N}`、`\s`，
归一化还要 NFC。Mojo 的 stdlib 里没有这些表，而**手写一份"差不多"的表
是最危险的做法**：它会在绝大多数输入上正确，只在个别脚本上悄悄错，然后
被 4560 条差分用例之一抓住 —— 或者更糟，没被抓住。

所以表是**从 Python 的 unicodedata 生成**的，而不是手写的；生成过程连同
Unicode 版本一起写进产物头部，谁都能重跑核对。

组合表同样由生成而非推导：`NFC(a + b) == c` 才写入，于是 Unicode 的
CompositionExclusions.txt 不必再手工维护一份 —— 被排除的组合自然不会
出现（这正是 fast-tokenizer 那类"看起来能跑"的实现最容易漏的地方）。

用法：

    python3 scripts/gen_unicode_tables.py
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src/alofa/tokenizer/unicode_data.mojo"

# Unicode 的 White_Space 属性（UCD PropList.txt）。Python 的 str.isspace()
# 与它并不完全一致（多了 1C–1F），所以这里用标准清单而不是 isspace()。
WHITE_SPACE = [
    0x0009, 0x000A, 0x000B, 0x000C, 0x000D, 0x0020, 0x0085, 0x00A0,
    0x1680,
    0x2000, 0x2001, 0x2002, 0x2003, 0x2004, 0x2005, 0x2006, 0x2007,
    0x2008, 0x2009, 0x200A,
    0x2028, 0x2029, 0x202F, 0x205F, 0x3000,
]

# 谚文（Hangul）音节用算法处理，不进表：11172 个音节会让表膨胀两个数量级。
HANGUL_SYL_BASE = 0xAC00
HANGUL_SYL_END = 0xD7A3


def category_ranges(prefixes: tuple[str, ...]) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start = None
    prev = -1
    for cp in range(sys.maxunicode + 1):
        hit = unicodedata.category(chr(cp)).startswith(prefixes)
        if hit and start is None:
            start = cp
        elif not hit and start is not None:
            ranges.append((start, prev))
            start = None
        if hit:
            prev = cp
    if start is not None:
        ranges.append((start, prev))
    return ranges


def build_decomposition() -> list[tuple[int, list[int]]]:
    out = []
    for cp in range(sys.maxunicode + 1):
        if HANGUL_SYL_BASE <= cp <= HANGUL_SYL_END:
            continue
        ch = chr(cp)
        nfd = unicodedata.normalize("NFD", ch)
        if len(nfd) > 1 or (len(nfd) == 1 and ord(nfd[0]) != cp):
            out.append((cp, [ord(c) for c in nfd]))
    return out


def build_composition(decomp: list[tuple[int, list[int]]]) -> list[tuple[int, int, int]]:
    """组合表 [(starter, mark, composite)]。

    左侧**必须是已经合好的那一半**，而不是原始分解串的第一个字符 —— 有些码位的
    规范分解是三项的（如 U+1E5D = 72 0323 0304），要先由 r + 下加点合出 U+1E5B，
    再与上横线合出 U+1E5D。只收录两两项分解的话，这类字符会被 NFC 拆散后就合不
    回去，`thiệt`、`ẩ` 这类常见越南语字都会错。

    是否收录仍然由权威实现说了算：只有 NFC(starter + mark) 真的等于 composite
    才写入，于是 CompositionExclusions 不必再手工维护一份。
    """
    out = []
    for cp, parts in decomp:
        if len(parts) < 2:
            continue
        starter = unicodedata.normalize("NFC", "".join(chr(p) for p in parts[:-1]))
        if len(starter) != 1:
            continue  # 前缀合不到一个字符上，就没有可作为左侧的 starter
        last = chr(parts[-1])
        if unicodedata.normalize("NFC", starter + last) == chr(cp):
            out.append((ord(starter), ord(last), cp))
    return sorted(out, key=lambda t: t[0] * 0x110000 + t[1])


def build_combining_class() -> list[tuple[int, int]]:
    out = []
    for cp in range(sys.maxunicode + 1):
        ch = chr(cp)
        ccc = unicodedata.combining(ch)
        if ccc:
            out.append((cp, ccc))
    return out


def emit_list(name: str, values: list[int], width: int = 8) -> str:
    lines = ["def %s() -> List[Int]:" % name, "    var out = List[Int]()"]
    for v in values:
        lines.append("    out.append(0x%06X)" % v)
    lines.append("    return out^")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    letters = category_ranges(("L",))
    numbers = category_ranges(("N",))
    decomp = build_decomposition()
    compose = build_composition(decomp)
    ccc = build_combining_class()

    flat_letters = [v for lo, hi in letters for v in (lo, hi)]
    flat_numbers = [v for lo, hi in numbers for v in (lo, hi)]
    flat_decomp: list[int] = []
    for cp, parts in decomp:
        flat_decomp.append(cp)
        flat_decomp.append(len(parts))
        flat_decomp.extend(parts)
    flat_compose: list[int] = []
    for a, b, cp in compose:
        flat_compose.extend((a, b, cp))

    header = '''"""Unicode property tables — **generated by `scripts/gen_unicode_tables.py`,
do not edit by hand**.

Source: Python's `unicodedata` (Unicode {version}). The pre-tokenizer needs
the regex classes p{{L}}, p{{N}} and s; NFC needs canonical decompositions,
combining classes and a composition table. Mojo's stdlib ships none of them,
and a hand-written approximation is worse than none: it agrees almost
everywhere and disagrees on one script, which is exactly how a wrong
tokenizer stays hidden.

Layout: range tables are flat `[lo, hi, lo, hi, ...]` arrays searched
binarily. Hangul syllables (AC00–D7A3) are handled algorithmically and are
absent here — listing all 11172 of them would be pure table bloat.
"""


def letter_ranges() -> List[Int]:
    """`p{{L}}` (regex letter class): {n_letters} ranges."""

'''.format(
        version=unicodedata.unidata_version,
        n_letters=len(letters),
    )

    body = ["    var out = List[Int]()"]
    body += ["    out.append(0x%06X)" % v for v in flat_letters]
    body += ["    return out^", ""]

    parts = [header, "\n".join(body)]
    parts.append(emit_list("number_ranges", flat_numbers))
    parts.append(emit_list("whitespace_points", WHITE_SPACE))
    parts.append(emit_list("decomposition_table", flat_decomp))
    parts.append(emit_list("composition_table", flat_compose))
    parts.append(emit_list("combining_class_table", [v for c, v in ccc for v in (c, v)]))

    text = "\n".join(parts)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")

    print(
        "letters=%d numbers=%d decomp=%d compose=%d ccc=%d -> %s (%.0f KB)"
        % (
            len(letters),
            len(numbers),
            len(decomp),
            len(compose),
            len(ccc),
            OUT,
            len(text) / 1024,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
